#服务器执行一次匹配的间隔时间
host.match.interval: 5
#匹配超时，会话被清理掉
host.match.timeout: 300
#超过匹配时间，系统自动匹配AI
host.match.auto: 10

# Redis数据库索引（默认为0）
spring.redis.database: 0  
# Redis服务器地址
spring.redis.host: localhost
# Redis服务器连接端口
spring.redis.port: 6379  
# Redis服务器连接密码（默认为空）
#spring.redis.password: yourpwd
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.lettuce.pool.max-active: 8  
# 连接池最大阻塞等待时间 
spring.redis.lettuce.pool.max-wait: -1ms
# 连接池中的最大空闲连接
spring.redis.lettuce.pool.max-idle: 8  
# 连接池中的最小空闲连接
spring.redis.lettuce.pool.min-idle: 0  
# 连接超时时间（毫秒）
spring.redis.timeout: 5000ms

#配置缓存相关
cache.default.expire-time: 200
cache.host.expire-time: 180
cache.host.name: hosts

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.cx.game: DEBUG
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
#OAuth2
#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8901/user

#Redis
redis.host: 127.0.0.1
redis.port: 6379