example.property: "I AM THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.jpa.show-sql: "true"
spring.jpa.properties.hibernate.hbm2ddl.auto: "update"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
spring.jpa.hibernate.naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3307/game?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&&serverTimezone=GMT%2B8"
spring.datasource.username: "root"
spring.datasource.password: "123456"
spring.datasource.max-idle: "10"
spring.datasource.max-wait: "10000"
spring.datasource.min-idle: "5"
spring.datasource.initial-size: "5"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.cx.game: DEBUG

#Eureka
eureka:
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#Hystrix
feign:
  hystrix:
    enabled: true
    
#使用Feign调用接口分两层，ribbon的调用和hystrix的调用，所以ribbon的超时时间和Hystrix的超时时间的结合就是Feign的超时时间
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true  #是否开启超时熔断
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms