# 内嵌tomcat线程最大数量，默认是200； 内存优化
server.tomcat.max-threads: 10

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.cx.game: DEBUG
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.20.1.3:8761/eureka/